### ISSUE TITLE
Uploading file functionality doesn't work for firefox container

### ISSUE THREAD

**Issue by IZaiarnyi** [aerokube/selenoid-images#122]
I'm using:
-  latest (3.13.1) C# selenium client library
-  latest (1.7.1) selenoid server
-  61.0 and 58.0 firefox docker images

```C#
 _fileInput.WaitForPresent().SendKeys(fullFilePath);


OpenQA.Selenium.WebDriverException : zip: not a valid zip file
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.Execute(String commandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.UploadFile(String localFile)
   at OpenQA.Selenium.Remote.RemoteWebElement.SendKeys(String text)
```

**This code works well either for chrome container or local run of firefox**

**Comment by vania-pooh** [comment]
Seems to be an issue in C# client: https://github.com/SeleniumHQ/selenium/pull/8586
