### ISSUE TITLE
Latest two opera images

### ISSUE THREAD

**Issue by O5ten** [aerokube/selenoid-images#23]
Running any of the latest two versions of opera docker images gives a nifty error message: 

```bash
node:11596) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[15:10:44] I/launcher - Running 1 instances of WebDriver
[15:10:44] I/hosted - Using the selenium server at http://:@localhost:4444/wd/hub
[15:10:45] E/launcher - unknown error: cannot find Opera binary
  (Driver info: OperaDriver=2.32 (cfa164127aab5f93e5e47d9dcf8407380eb42c50),platform=Linux 4.4.0-101-generic x86_64)
[15:10:45] E/launcher - WebDriverError: unknown error: cannot find Opera binary
  (Driver info: OperaDriver=2.32 (cfa164127aab5f93e5e47d9dcf8407380eb42c50),platform=Linux 4.4.0-101-generic x86_64)
    at Object.checkLegacyResponse ($HOME\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse ($HOME\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response ($HOME\node_modules\selenium-webdriver\lib\http.js:441:30)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: WebDriver.createSession()
  at Function.createSession ($HOME\node_modules\selenium-webdriver\lib\webdriver.js:769:24)
  at createDriver ($HOME\node_modules\selenium-webdriver\index.js:170:33)
  at Builder.build ($HOME\node_modules\selenium-webdriver\index.js:635:14)
  at Hosted.getNewDriver ($HOME\node_modules\protractor\built\driverProviders\driverProvider.js:53:33)
  at Runner.createBrowser ($HOME\node_modules\protractor\built\runner.js:195:43)
  at q.then.then ($HOME\node_modules\protractor\built\runner.js:339:29)
  at _fulfilled ($HOME\node_modules\protractor\node_modules\q\q.js:834:54)
  at self.promiseDispatch.done ($HOME\node_modules\protractor\node_modules\q\q.js:863:30)
  at Promise.promise.promiseDispatch ($HOME\node_modules\protractor\node_modules\q\q.js:796:13)
  at $HOME\node_modules\protractor\node_modules\q\q.js:556:49
  at runSingle ($HOME\node_modules\protractor\node_modules\q\q.js:137:13)
  at flush ($HOME\node_modules\protractor\node_modules\q\q.js:125:13)
  at _combinedTickCallback (internal/process/next_tick.js:131:7)
  at process._tickCallback (internal/process/next_tick.js:180:9)
  at Function.Module.runMain (module.js:611:11)
  at startup (bootstrap_node.js:158:16)
  at bootstrap_node.js:598:3

[15:10:45] E/launcher - Process exited with error code 199
```
All it tells me is that something is strange with the docker image. 

It's running latest and greatest selenoid from today with the following capabilities translated to the real selenium capabilities: 
```
Protractor-options:  { sut: 'http://baseurl',
  browser:
   { name: 'opera',
     version: '',
     vnc: { enabled: true },
     recording: { name: 'protractor-test.mp4', enabled: false } },
  selenium: { port: '4444', host: 'localhost', username: '', password: '' },
  specs: [ '**/*.js' ] }
```

**Comment by aandryashin** [comment]
You have to specify operabinary as described here:
http://aerokube.com/selenoid/latest/#_opera



19 дек. 2017 г. 5:20 ПП пользователь "Mikael Östberg" <
notifications@github.com> написал:

**Comment by vania-pooh** [comment]
... and that's a bug in Operadriver.

**Comment by O5ten** [comment]
Ah, look at that. I missed that detail of the documentation. Let's close this issue. 

Adding the operaOptions: ``` { binary: '/usr/bin/opera' } ``` resolved it.
